### ISSUE TITLE
“Open Preview Automatically” creates 2 tabs

### ISSUE THREAD

**Issue by tedw** [josa42/atom-svg-preview#30] opened 2016-07-14 17:43 UTC
Love this package, great work! Only issue is that it creates two preview tabs when all of the options are selected. My colleague couldn’t reproduce the issue so I'm guessing it’s related to another package. Have you heard of this happening before, and do you know of any incompatibilities with other packages?

<details><summary>

My installed packages and themes FWIW</summary>

- advanced-open-file
- atom-beautify
- atom-mac-theme
- atom-material-syntax
- atom-wrap-in-tag
- autoclose-html
- autocomplete-nunjucks
- autocomplete-paths
- base16-ocean-dark-spacegray
- color-picker
- editorconfig
- emmet
- fedtastic-syntax
- file-icons
- firewatch-syntax
- genesis-ui
- git-time-machine
- github-atom-light-syntax
- ir-black-syntax
- language-babel
- language-nunjucks
- linter
- linter-jshint
- linter-scss-lint
- livereload
- markdown-preview-plus
- markdown-scroll-sync
- merge-conflicts
- minimap-cursorline
- minimap-find-and-replace
- minimap-git-diff
- minimap-hide
- minimap-highlight-selected
- minimap-linter
- minimap-pigments
- minimap-split-diff
- pigments
- pretty-json
- project-manager
- script
- sort-lines
- spacegray-dark-ui
- split-diff
- Sublime-Style-Column-Selection
- svg-preview
- tabs-to-spaces
- todo-show
- wordcount
  </details>

<br>I’m running Atom 1.8.0 on El Capitan.

Any help would be much appreciated. Thanks!

**Comment by josa42** [comment] 2016-07-27 22:26
@tedw Unfortunately I cannot reproduce this issue. Could you try to find out which package it conflicts with?

**Comment by sompylasar** [comment] 2016-12-26 05:54
@josa42 I was trying to use `package-cop` to bisect the failing package and discovered that despite `svg-preview` is shown as unloaded, the preview still appears when I open an SVG, so I think there is an issue here with at least unloading the `svg-preview` package. This means the resources taken by the package, e.g. subscriptions to events, aren't released upon deactivation. And this may be an evidence that there may be a double subscription to some event, resulting in double handling of an event, which may result in opening two or more preview tabs. I'll look into the code to see if I can find the bug.

**Comment by sompylasar** [comment] 2016-12-26 06:18
Besides the missing `deactivate` handler which must unsubscribe from all the events you subscribe in `activate`, [the `onDidChangeActivePaneItem` handler triggers twice (or thrice?)](https://github.com/josa42/atom-svg-preview/blob/4b096671e8a5a3570754045616ee44a28440101c/lib/main.js#L46) resulting in [`addPreviewForEditor` to be called twice](https://github.com/josa42/atom-svg-preview/blob/4b096671e8a5a3570754045616ee44a28440101c/lib/main.js#L72), and that function [is not protected from being called twice for the same file](https://github.com/josa42/atom-svg-preview/blob/4b096671e8a5a3570754045616ee44a28440101c/lib/main.js#L157). Moreover, [the promise handler](https://github.com/josa42/atom-svg-preview/blob/4b096671e8a5a3570754045616ee44a28440101c/lib/main.js#L158) may trigger at any later time, even after the package is deemed deactivated, so that may result in unexpected behavior unless the call is protected from that case.

I'd suggest you to learn and fix all the resource allocation/deallocation in the code, because the code contains quite a lot of errors because the proper allocation/deallocation of resources is missing.

**Comment by josa42** [comment] 2016-12-30 08:44
@sompylasar While I thank you for research the problem, I'd suggest you to fix it and submit a pr instead of posting arrogant comments.

**Comment by josa42** [comment] 2016-12-30 10:04
Should be fixed in `0.10.2`

@tedw Please reopen if it still occurs.

**Closed by josa42** 2016-12-30 10:04 UTC
Labels: bug

**Comment by tedw** [comment] 2017-02-22 00:07
Fixed, thanks all!
