### ISSUE TITLE
Uncaught TypeError: item.getText is not a function

### ISSUE THREAD

**Issue by vert2x** [josa42/atom-svg-preview#27] opened 2016-01-15 09:07 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.2
**Thrown From**: [svg-preview](https://github.com/josa42/atom-svg-preview) package, v0.7.3

### Stack Trace

Uncaught TypeError: item.getText is not a function

```
At /Users/vnaboka/.atom/packages/svg-preview/lib/main.coffee:90

TypeError: item.getText is not a function
    at Object.module.exports.isSvgEditor (/Users/vnaboka/.atom/packages/svg-preview/lib/main.coffee:90:38)
    at Object.module.exports.onDidChangeActivePaneItem (/Users/vnaboka/.atom/packages/svg-preview/lib/main.coffee:79:8)
    at /Users/vnaboka/.atom/packages/svg-preview/lib/main.coffee:63:8
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:333:27
    at Pane.module.exports.Pane.observeActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:196:7)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:331:42
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at PaneContainer.module.exports.PaneContainer.setActivePane (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:196:22)
    at Pane.module.exports.Pane.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:623:15)
    at Pane.module.exports.Pane.focus (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:207:21)
    at atom-pane.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:50:23)
```

### Commands

```
     -8:12.1.0 svg-preview:toggle (atom-text-editor.editor.is-focused)
     -8:03.0 core:close (div.svg-preview.native-key-bindings)
     -6:54.5.0 svg-preview:toggle (atom-text-editor.editor.is-focused)
  2x -6:53.4.0 core:close (div.svg-preview.native-key-bindings)
     -6:41.1.0 svg-preview:toggle (atom-text-editor.editor.is-focused)
  2x -6:08.0 core:close (div.image-view)
     -5:25.2.0 settings-view:open (atom-text-editor.editor.is-focused)
     -5:21.5.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -5:20.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:37.9.0 core:close (div.svg-preview.native-key-bindings)
     -3:04.5.0 editor:log-cursor-scope (atom-text-editor.editor.is-focused)
     -2:57.4.0 preview-inline:show (atom-text-editor.editor.is-focused)
     -2:56.1.0 editor:log-cursor-scope (atom-text-editor.editor.is-focused)
  2x -2:32.2.0 core:close (div.package-detail.panels-item)
```

### Config

```json
{
  "core": {
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "local-server-web-view",
      "autohide-tree-view",
      "w3c-validation",
      "vim-mode",
      "keybinding-resolver",
      "preview-inline"
    ],
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [
      "atom-beautify"
    ]
  },
  "svg-preview": {
    "openPreviewAutomatically": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.21
atom-commander, v0.5.1
bottom-dock, v0.3.7
browser-refresh, v0.9.0
emmet, v2.3.17
gulp-manager, v0.2.18
open-in-browser, v0.4.6
project-manager, v2.7.3
remote-edit, v1.8.23
svg-preview, v0.7.3
sync-settings, v0.6.0
tree-view-git-branch, v0.0.6

# Dev
No dev packages
```

**Comment by josa42** [comment] 2016-01-28 11:44
Can you give me steps to reproduce this? #

**Comment by josa42** [comment] 2016-02-28 22:00
I am closing this, since there is no feedback. Please reopen, if the error still occurs.

**Closed by josa42** 2016-02-28 22:00 UTC
Labels: more-information-needed
